#!/usr/bin/perl

# Copyright (c) 2015, cPanel, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Creates the contents typically needed for Apache's errordocument.conf.
# This document allows users to create .shtml pages which allow them to
# customize their error pages according to cPanel & WHM standards.
#
# NOTE: This performs similar but more general functionality as:
#   Cpanel::AdvConfig::apache::includes::init()

use strict;
use warnings;

package generate_errordoc_conf;

use HTTP::Status ();

our @DefaultErrorCodes = ( 400 .. 417, 422 .. 424, 500 .. 507, 510 );

sub generate_errordoc {
    for my $code_num (@DefaultErrorCodes) {
        my $code_type = HTTP::Status::status_message($code_num);
        printf( "# %d - %s\n", $code_num, $code_type || '<Unknown HTTP Error Code>' );
        print <<"END_ENTRY";
<If "-f '%{DOCUMENT_ROOT}/$code_num.shtml'">
    ErrorDocument $code_num /$code_num.shtml
</If>
<Else>
    ErrorDocument $code_num default
</Else>

END_ENTRY
    }
}

package main;

generate_errordoc_conf::generate_errordoc() unless caller();
